[workspace]
members = [
  "apps/cli",
  "apps/desktop/src-tauri/",
  "libs/model/macro",
  "libs/model",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
# Helpers
anyhow = { version = "1.0.89" }
thiserror = { version = "1.0.64" }
clap = { version = "4.5.20", features = ["derive"] }
chrono = { version = "0.4.38" }
derive_builder = { version = "0.20.2" }
tap = { version = "1.0.1" }
directories = { version = "5.0.1" }

# Serialization
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
serde_yml = { version = "0.0.12" }
serde_with = { version = "3.11.0" }
heck = { version = "0.5.0" }
shell-words = { version = "1.1.0" }
ts-rs = { version = "10.0.0", features = ["chrono-impl"] }
config = { version = "0.14.0" }

# OCI
oci-spec = { version = "0.7.0" }

# Tracing
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = [
  "parking_lot",
  "tracing",
] }

# Database
surrealdb = { version = "2.0.4", features = ["kv-rocksdb", "kv-mem"] }

# Async
tokio = { version = "1.40.0", features = ["process", "sync"] }
tokio-util = { version = "0.7.12", features = ["io", "rt"] }
tokio-stream = { version = "0.1.16", features = ["io-util"] }
futures = { version = "0.3.31" }

# Macro helpers
syn = { version = "2.0.79" }
quote = { version = "1.0.37" }
proc-macro2 = { version = "1.0.87" }
darling = { version = "0.20.10" }

# Tauri
tauri = { version = "2.0.2", features = ["macos-private-api", "tray-icon"] }
tauri-build = { version = "2.0.1", features = [] }

[workspace.lints.clippy]
type_complexity = 'allow'
single_match = 'allow'
collapsible_else_if = 'allow'

[workspace.metadata.cross.target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross:local"

[workspace.metadata.cross.target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"
