// This file has been generated by Specta. DO NOT EDIT.

export type Script = {
  id: ThingsDef | null;
  name: string;
  command: string;
  args: string[];
  env: { [key in string]: string };
  workingDir: string | null;
};

export type ScriptRun = {
  id: ThingsDef | null;
  script: Script;
  spawnedAt: string;
  finishedAt: string | null;
  exitCode: number | null;
  log: ScriptRunLog[];
};

export type ScriptRunLog =
  | { stdout: { txt: string; ts: string } }
  | { stderr: { txt: string; ts: string } };

export type ThingsDef = { tb: string; id: string };
